services:
      recognize.wysiwyg.form.type.wysiwyg:
              class: Recognize\WysiwygBundle\Form\Type\WysiwygType
              arguments: [%recognize_wysiwyg.default%]
              tags:
                  -  { name: form.type, alias: "wysiwyg" }

      recognize.wysiwyg.form.type.inline_wysiwyg:
              class: Recognize\WysiwygBundle\Form\Type\InlineWysiwygType
              arguments: [%recognize_wysiwyg.default%]
              tags:
                  -  { name: form.type, alias: "inline_wysiwyg" }

      recognize.wysiwyg.ckeditor.locales:
              class: Recognize\WysiwygBundle\Twig\CkeditorLocaleFunction
              arguments: [@service_container]
              public: false
              tags:
                   - { name: twig.extension }
